### ISSUE TITLE
Related query params route mixin for comparison

### ISSUE THREAD

**Issue by 2468ben** [knownasilya/ember-query-params#11]
Rather than throwing this in Slack and having it disappear in a day, I'm just gonna link to it here:

[Query Params Mixin Gist](https://gist.github.com/2468ben/0855177da7ecba88db6743e6e311e119)

My mixin's more about figuring out what QPs did change on a route, rather than changing them. I tried setting QPs directly in a controller but always ended up hitting some crazy race conditions. So now I only set them by making a new transition:

``` javascript
this.transitionTo({queryParams: {foo: 'bar'}})
```

And I add a reference to the application route in the query-params service, so I can call

``` javascript
this.get('query-params.appRoute').transitionTo(...)
```

directly from components, instead bubbling lots of actions.

I documented all the weird routing quirks I had to use, hopefully some bit of it is useful.

**Comment by knownasilya** [comment]
So `queryParamsDidChange` seems like a valid way to update QPs on the service. I's not documented, even as private.. @rwjblue do you have any thoughts on that action?

Might be worthwhile to create the mixin for the route instead, since we can access the controller from there and setup the autoupdate action as well.

**Comment by 2468ben** [comment]
I didn't realize it was a non-documented function, sorry! I've been playing with queryparams since they were in canary, so I saw that action mentioned several time but I don't see it in the docs now.

Also I didn't notice before that queryParamsDidChange isn't an empty hook, so in my gist I should definitely call that action's _super.

**Comment by knownasilya** [comment]
Give master a try. I converted the autosubscribe mixin to be used with the route and uses that action to update the values in the service. This makes only one mixin required and will still be usable when controllers are gone.

**Comment by 2468ben** [comment]
Cool, I'll try plugging it in my app today or tomorrow, thanks for making this addon!
