### ISSUE TITLE
Async `model` hook + reloading QPs from the the URL crashes

### ISSUE THREAD

**Issue by jbourassa** [knownasilya/ember-query-params#18]
Hey,

I gave `ember-query-params` a shot as I was updating my app to Ember 2, but ran into a crash when doing a full load (eg browser refresh) of a page that has query params and an async model hook.

Here's a _very_ simple reproduction repo : [jbourassa/ember-qp-issue](https://github.com/jbourassa/ember-qp-issue)

Booting this app and opening http://localhost:4200/?orderDir=desc should trigger the issue.

This should print two errors in the console:

```
Error while processing route: index delegate is not a function TypeError: delegate is not a function
    at _emberRuntimeMixinsController.default.reopen._qpChanged 
```

and

```
TypeError: delegate is not a function
    at _emberRuntimeMixinsController.default.reopen._qpChanged (ember.debug.js:24108)
```

I'm not exactly sure why this happens, but is there anything I can do to help get this fixed?

**Comment by rmachielse** [comment]
Any updates on this? I'm having the same problem

**Comment by knownasilya** [comment]
Will have a look, thanks for the ping.

**Comment by knownasilya** [comment]
Give it a try with Ember 2.4.6, I think they reverted some of the "fixes" to QPs.

**Comment by jbourassa** [comment]
This is probably stale, let's close this.
