### ISSUE TITLE
Does ember-query-params support array query params?

### ISSUE THREAD

**Issue by remkoboschker** [knownasilya/ember-query-params#19]
I have tried and did not mange. If I set a value it is serialized as a single value although the queryparam is initialized to an array on the controller.

**Comment by knownasilya** [comment]
What version of Ember are you using with EQP?

**Comment by remkoboschker** [comment]
Hi, 2.6.0

**Comment by knownasilya** [comment]
Try 2.4.6

**Comment by aroberts** [comment]
Any progress on this? I have array QPs and I depend on 2.7.0

**Comment by knownasilya** [comment]
Give setting the type to array, e.g. 

``` js
queryParams: [{
  test: { type: 'array' }
}]
```

**Comment by knownasilya** [comment]
Otherwise you might have better luck with using a string and deserializing to an array: `arr.split(',').map(i => i.trim())`.

Ember has a plethora of bugs relating to serializing and deserializing QPs.

**Comment by cwarny** [comment]
@knownasilya 's above suggestion (setting the type to 'array') works perfectly for me. I guess this can be closed? However, I don't think this is mentioned in the guides

**Comment by knownasilya** [comment]
Good to know it worked for you.

**Comment by jevanlingen** [comment]
Addition to https://github.com/knownasilya/ember-query-params/issues/19#issuecomment-236040566:

The URL looks like `?test=[1,2]` for integers,  `?test=[1.1,2.2]` for doubles and `?test=["some","things"]` for strings.
