### ISSUE TITLE
transitionTo adding quotes around array queryString

### ISSUE THREAD

**Issue by pk1m** [knownasilya/ember-query-params#25]
i have a query string thats an array

`&array=%5B"test"%5D`

when using transitionTo it gets converted to 

`&array="%5B%5C"test%5C"%5D"`

link-to works fine, any idea what is causing this and how to fix this?

Thanks

**Comment by knownasilya** [comment]
Maybe try setting the type manually?

```js
export default Route.extend({
  queryParams: {
    array: {
      type: 'array'
    }
  },
});
```

**Comment by pk1m** [comment]
Thanks for the quick reply, still reserializes it to `&array="%5B%5C"test%5C"%5D"`. hmm seems like it would be a common issue maybe its my setup.

**Comment by knownasilya** [comment]
I would recommend not using this addon instead maybe try https://github.com/NullVoxPopuli/ember-query-params-service or https://github.com/offirgolan/ember-parachute.

**Comment by pk1m** [comment]
heh, that would require a bit more work.  I just opened a PR request for a fix if you could take a look

**Comment by knownasilya** [comment]
v2.1.1 published, give it a try.
