### ISSUE TITLE
Remove module scope `map` usage.

### ISSUE THREAD

**Issue by rwjblue** [knownasilya/ember-query-params#4]
Using this with multiple acceptance test would have state / callbacks from prior tests.  We should entagle the `map` with the service.

**Comment by knownasilya** [comment]
The service, or the mixin?

**Comment by knownasilya** [comment]
``` js
Mixin.create({
  init() {
    this._super(...arguments);
    this.map = new Map();
  }
})
```

or on the service, and document that the mixin needs a map object.

**Comment by rwjblue** [comment]
I would put it in the `Mixin` (since it is required for functionality).
