### ISSUE TITLE
Unsubscribe

### ISSUE THREAD

**Issue by knownasilya** [knownasilya/ember-query-params#6]
I think we need it since we store the functions in an array, although we don't call them if the target is destroyed/ing (only for auto).

**Comment by knownasilya** [comment]
Could we override `destroy`, since controllers are really `Ember.Object` instances? Not sure if that is how they are torn down in Ember cc @rwjblue

**Comment by rwjblue** [comment]
Implement willDestroy on the controller and unsubscribe from there. Might want a mixin for controllers too then...

**Comment by knownasilya** [comment]
In the works #9, although trying to figure out how to create a controller from the container for the mixin test..

**Comment by joukevandermaas** [comment]
@rwjblue do controllers ever even get destroyed? I thought they were long-living singletons.

**Comment by rwjblue** [comment]
They are destroyed at app tear down, but it is possible with this addon to bind a QP into a component or something too so cleaning up still makes sense.

**Comment by knownasilya** [comment]
In v1.1.0
