### ISSUE TITLE
Mixin for autosubscribe

### ISSUE THREAD

**Issue by joukevandermaas** [knownasilya/ember-query-params#9]
Have you considered adding a mixin to add the autosubscribe behavior to controllers? It would be used like this:

``` js
import Ember from 'ember';
import QPAutoSubscribe from 'ember-query-params/mixins/query-params-controller';
const { Controller } = Ember;

export default Controller.extend(QPAutoSubscribe, {
  queryParams: [
    // ...
  ]
});
```

This would inject the service and call `autoSubscribe(this)` in `init`. By adding this into a mixin, we can e.g. auto-inject it in all controllers through an initializer.

**Comment by knownasilya** [comment]
Sounds like a great idea!

**Comment by knownasilya** [comment]
In v1.1.0
